version: 2

jobs:
  pupernetes:
    machine: true
    working_directory: /home/circleci/your-project-directory
    environment:
      DEBIAN_FRONTEND: "noninteractive"
      SUDO_USER: "circleci"
    steps:
      - checkout
      - run:
          name: download
          command: sudo curl -Lf https://github.com/DataDog/pupernetes/releases/download/v0.11.0/pupernetes -o /usr/local/bin/pupernetes && sudo chmod +x /usr/local/bin/pupernetes
      - run:
          name: apt
          command: sudo apt-get update -qq && sudo apt-get install -yqq systemd
      - run:
          name: run
          command: sudo /usr/local/bin/pupernetes daemon run sandbox/ --job-type systemd --kubectl-link /usr/local/bin/kubectl --kubeconfig-path $HOME/.kube/config --dns-check --hyperkube-version=1.14.0
      - run:
          name: kubectl
          command: kubectl get all
      - run:
          name: install helm
          environment:
            EXE_FOLDER: /usr/local/bin
          command: |
            curl -sLo_ https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz
            tar -zxvf _
            sudo mv ./linux-amd64/helm ${EXE_FOLDER}/
            sudo chmod +x $EXE_FOLDER/helm
            rm _
            rm -rf linux-amd64

      - run:
          name: Install the latest Istio
          command: |
            helm repo add istio.io https://storage.googleapis.com/istio-release/releases/1.4.3/charts/
            
            kubectl create namespace istio-system
            helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f -
            kubectl -n istio-system wait --for=condition=complete job --all


            # Labelling namespace default for sidecar injection
            kubectl label namespace default istio-injection=enabled

            # Showing all namespaces and the sidecar injection status
            kubectl get namespace -L istio-injection
      - run:
          name: something
          command: echo "let's go ..."

workflows:
  version: 2
  daemon:
    jobs:
      - pupernetes
