version: 2

jobs:
  make_file:
    docker:
      - image: bash
    steps:
      - checkout
      - run: mkdir plans
      - run: echo "hello" > plans/hello.txt
      - persist_to_workspace:
          root: .
          paths:
            - plans
  get_file:
    docker:
      - image: bash
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: cat ~/project/plans/hello.txt

workflows:
  version: 2
  daemon:
    jobs:
      - make_file
      - get_file:
          requires:
            - make_file
