version: 2.1
orbs:
  kubernetes: circleci/kubernetes@1.3.0

jobs:
  kubernetes:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run:
          name: kubectl
          command: kubectl get all 

workflows:
  version: 2
  workflow:
    jobs:
      - kubernetes
