version: 2

jobs:
  semantic_release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Run semantic_release
          command: |
            npm install @semantic-release/exec
            npx semantic-release

  scratchpad_google_cloud_sdk:
    docker:
      - image: google/cloud-sdk
    steps:
      - run: echo "Restart with SSH"
workflows:
    version: 2
    workflow:
      jobs:
        - semantic_release
        - scratchpad_google_cloud_sdk
