version: 2

jobs:
  pupernetes:
    machine: true
    working_directory: /home/circleci/your-project-directory
    environment:
      DEBIAN_FRONTEND: "noninteractive"
      SUDO_USER: "circleci"
    steps:
      - checkout
      - run:
          name: download
          command: sudo curl -Lf https://github.com/DataDog/pupernetes/releases/download/v0.11.0/pupernetes -o /usr/local/bin/pupernetes && sudo chmod +x /usr/local/bin/pupernetes
      - run:
          name: apt
          command: sudo apt-get update -qq && sudo apt-get install -yqq systemd
      - run:
          name: run
          command: sudo /usr/local/bin/pupernetes daemon run sandbox/ --job-type systemd --kubectl-link /usr/local/bin/kubectl --kubeconfig-path $HOME/.kube/config --dns-check --hyperkube-version=1.14.0
      - run:
          name: kubectl
          command: kubectl get all
      - run:
          name: install helm
          environment:
            EXE_FOLDER: /usr/local/bin
          command: |
            curl -sLo_ https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz
            tar -zxvf _
            sudo mv ./linux-amd64/helm ${EXE_FOLDER}/
            sudo chmod +x $EXE_FOLDER/helm
            rm _
            rm -rf linux-amd64

      - run:
          name: Install the latest Istio
          command: |
            ISTIO_TMP_DIR=$(mktemp -d)
            cd "$ISTIO_TMP_DIR"
            curl -L https://github.com/istio/istio/releases/download/1.3.3/istio-1.3.3-linux.tar.gz | tar xz
            ISTIO_PATH="$ISTIO_TMP_DIR/$(ls)"
            cd "$ISTIO_PATH"
            
            helm install "$ISTIO_PATH/install/kubernetes/helm/istio-init" --name istio-init --namespace istio-system
            
            # Sleep for 30 seconds for the CRD's to be added properly (TODO fix this)
            sleep 30
            
            helm install "$ISTIO_PATH/install/kubernetes/helm/istio" \
                --name istio \
                --namespace istio-system \
                --set gateways.istio-ingressgateway.type=NodePort
                
            # Get names of all Istio deployments
            DEPLOYMENT_NAMES=$(kubectl get deployment -o=json --namespace istio-system | jq ".items[].metadata.name")

            # Wait for all Istio services
            while read -r line; do
                echo "Checking deployment of $line"
                kubectl rollout status -w "deployment/$line" --namespace=istio-system
            done <"$DEPLOYMENT_NAMES"

            # Labelling namespace default for sidecar injection
            kubectl label namespace default istio-injection=enabled

            # Showing all namespaces and the sidecar injection status
            kubectl get namespace -L istio-injection
      - run:
          name: something
          command: echo "let's go ..."

workflows:
  version: 2
  daemon:
    jobs:
      - pupernetes
