version: 2.1

jobs:
  testing_benchmark_compare:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout:
          path: /tmp/unused
      - run:
          name: clone benchmarkdotnet master
          working_directory: /tmp/benchmarkdotnet-master-1
          command: git clone https://github.com/dotnet/BenchmarkDotNet.git
      - run:
          name: clone benchmarkdotnet master (another copy)
          working_directory: /tmp/benchmarkdotnet-master-2
          command: git clone https://github.com/dotnet/BenchmarkDotNet.git
      - run:
          name: Run sample benchmarks on 1
          working_directory: /tmp/benchmarkdotnet-master-1/BenchmarkDotNet/samples/BenchmarkDotNet.Samples
          command: dotnet run -c Release --filter * --join --artifacts /tmp/artifacts-run-1
      - run:
          name: Run sample benchmarks on 2
          working_directory: /tmp/benchmarkdotnet-master-2/BenchmarkDotNet/samples/BenchmarkDotNet.Samples
          command: dotnet run -c Release --filter * --join --artifacts /tmp/artifacts-run-2

      - run:
          name: Compare benchmarks from 1 and 2
          working_directory: /tmp/benchmark-comparer
          command: |
            git clone https://github.com/dotnet/performance.git
            cd src/tools/ResultsComparer
            dotnet run \
              --base "/tmp/artifacts-run-1" \
              --diff "/tmp/artifacts-run-2" \
              --threshold 1% --top 10

workflows:
  workflow:
    jobs:
      - testing_benchmark_compare
