version: 2

jobs:
  scratchpad:
    docker:
      - image: google/cloud-sdk
        environment:
          TEST: $TEST_DEV
    steps:
      - run: echo hello
      - run: echo $TEST
workflows:
    version: 2
    workflow:
      jobs:
        - scratchpad