version: 2

jobs:
  scratch:
    machine:
      image: ubuntu-1604:201903-01
      environment:
        CHANGE_MINIKUBE_NONE_USER: true
        KUBECONFIG: /home/circleci/.kube/config
        MINIKUBE_WANTUPDATENOTIFICATION: false
        MINIKUBE_WANTREPORTERRORPROMPT: false
        MINIKUBE_HOME: /home/circleci
        DEBIAN_FRONTEND: noninteractive
        SUDO_USER: circleci
    steps:
      - checkout
      - run: sudo .circleci/install-minikube.sh


workflows:
  version: 2
  daemon:
    jobs:
      - scratch