version: 2

jobs:
  pupernetes:
    machine: true
    working_directory: /home/circleci/your-project-directory
    environment:
      DEBIAN_FRONTEND: "noninteractive"
      SUDO_USER: "circleci"
    steps:
      - checkout
      - run:
          name: download
          command: sudo curl -Lf https://github.com/DataDog/pupernetes/releases/download/v0.9.0/pupernetes -o /usr/local/bin/pupernetes && sudo chmod +x /usr/local/bin/pupernetes
      - run:
          name: apt
          command: sudo apt-get update -qq && sudo apt-get install -yqq systemd
      - run:
          name: run
          command: sudo /usr/local/bin/pupernetes daemon run sandbox/ --job-type systemd --kubectl-link /usr/local/bin/kubectl --kubeconfig-path $HOME/.kube/config --dns-check
      - run:
          name: kubectl
          command: kubectl get all
      - run:
          name: install helm
          environment:
            EXE_FOLDER: /usr/local/bin
            HELM: 2.14.2
          command: |
            curl -sLo_ https://storage.googleapis.com/kubernetes-helm/helm-v${HELM}-linux-amd64.tar.gz
            tar -zxvf _
            sudo mv ./linux-amd64/helm ${EXE_FOLDER}/
            sudo chmod +x $EXE_FOLDER/helm
            rm _
            rm -rf linux-amd64
      - run:
          name: Connect Helm with Pupernetes
          command: |
            kubectl create serviceaccount --namespace kube-system tiller
            kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
            helm init --service-account tiller --upgrade --wait

      - run:
          name: Install the latest Istio
          command: |
            ISTIO_TMP_DIR=$(mktemp -d)
            cd "$ISTIO_TMP_DIR"
            curl -L https://git.io/getLatestIstio | sh -
            ISTIO_PATH="$ISTIO_TMP_DIR/$(ls)"
            cd -

            helm install 
              "$ISTIO_PATH/install/kubernetes/helm/istio" \
              --name istio --namespace istio-system \
              --values "$ISTIO_PATH/install/kubernetes/helm/istio/values-istio-minimal.yaml" \
              --wait
      - run:
          name: something
          command: echo "let's go ..."

workflows:
  version: 2
  daemon:
    jobs:
      - pupernetes
