version: 2

jobs:
  test_docker_in_docker:
    docker:
      - image: docker:18.09.1-dind
    steps:
      - setup_remote_docker:
          version: 18.09.1
      - run: echo hello

  pupernetes:
    machine: true
    working_directory: /home/circleci/your-project-directory
    environment:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - run:
          name: download
          command: sudo curl -Lf https://github.com/DataDog/pupernetes/releases/download/v0.9.0/pupernetes -o /usr/local/bin/pupernetes && sudo chmod +x /usr/local/bin/pupernetes
      - run:
          name: apt
          command: sudo apt-get update -qq && sudo apt-get install -yqq systemd
      - run:
          name: run
          command: sudo /usr/local/bin/pupernetes daemon run sandbox/ --job-type systemd --kubectl-link /usr/local/bin/kubectl --kubeconfig-path $HOME/.kube/config --dns-check
      - run:
          name: kubectl
          command: kubectl get all
      - run:
          name: something
          command: echo "let's go ..."

workflows:
  version: 2
  daemon:
    jobs:
      - pupernetes
      - test_docker_in_docker
