version: 2

jobs:
  scratch:
    machine:
      user: root
      image: ubuntu-1604:201903-01
      environment:
        CHANGE_MINIKUBE_NONE_USER: true
        KUBECONFIG: /home/root/.kube/config
        MINIKUBE_WANTUPDATENOTIFICATION: false
        MINIKUBE_WANTREPORTERRORPROMPT: false
        MINIKUBE_HOME: /home/root
        DEBIAN_FRONTEND: noninteractive
        SUDO_USER: root
        user: node
    steps:
      - checkout
      - run: .circleci/install-minikube.sh


workflows:
  version: 2
  daemon:
    jobs:
      - scratch