version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.11.0

jobs:
  kubernetes:
    docker:
      - image: debian:10
    steps:
      - checkout
      - kube-orb/install-kubectl
      - run:
          name: kubectl
          command: kubectl get all

workflows:
  version: 2
  workflow:
    jobs:
      - kubernetes
